# Generated by Django 4.1.4 on 2022-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='photo')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='description')),
            ],
        ),
    ]
