# Generated by Django 4.1.4 on 2022-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_to_be_played',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Github\\Desarrollo Web\\Pagina-Videojuegos\\images/', verbose_name='photo'),
        ),
    ]
