# Generated by Django 4.1.4 on 2022-12-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_alter_game_available_to_be_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='available_to_be_played',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Github\\Desarrollo Web\\Pagina-Videojuegos\\images/', verbose_name='image'),
        ),
    ]
